version: '3.8'

services:
  embedding-service:
    build:
      context: ./python/embedding_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    environment:
      - PORT=8000
      - LOG_LEVEL=INFO
      # API keys (replace with your actual keys or use .env file)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - COHERE_API_KEY=${COHERE_API_KEY:-}
      - HF_API_TOKEN=${HF_API_TOKEN:-}
    volumes:
      - ./model_cache:/app/model_cache

  vectron:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/vectron/data
    restart: unless-stopped
    environment:
      - RUST_LOG=info
      - EMBEDDING_SERVICE_URL=http://embedding-service:8000
      - EMBEDDING_MODEL=minilm  # Optional: specify default model
    depends_on:
      - embedding-service

  dashboard:
    build:
      context: ./web/dashboard
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: unless-stopped
    depends_on:
      - embedding-service
      - vectron
