global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'embedding-service'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['embedding-service:8002']
        labels:
          service: 'vectron-embedding'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-metrics'

rule_files:
  - 'alerts.yml' 